name: HMTL to PDF with Puppeteer

on: push

jobs:
  printout:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          check-latest: true
      
      - name: Install dependencies
        run: npm install puppeteer

      - name: Execute shell
        run: |
          - ls
          - node scripts/setup-npm-version.js
