name: HMTL to PDF with Puppeteer

on: push

jobs:
  printout:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          check-latest: true
      
      - name: Install puppeteer
        run: npm install puppeteer

      - run: ls
      - run: node -h
      - run: npm ls

      - run: node print.js pullQuote.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

